name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.YOUR_SERVER_IP }}
          username: ${{ secrets.YOUR_SERVER_USER }}
          key: ${{ secrets.YOUR_SERVER_SSH_KEY }}
          script: |
            # 登录阿里云容器镜像仓库
            docker login --username=${{ secrets.ALIYUN_USER }} --password=${{ secrets.ALIYUN_PASS }} crpi-kdr9fgca88mf2q5d.cn-hangzhou.personal.cr.aliyuncs.com

            # 拉取最新镜像
            docker pull crpi-kdr9fgca88mf2q5d.cn-hangzhou.personal.cr.aliyuncs.com/kktt_mic/web_service_test:latest

            # 停止并删除旧容器（如果有）
            docker stop web_service_test || true
            docker rm web_service_test || true

            # 启动新容器（根据你实际需要调整端口、env等参数）
            docker run -d --name web_service_test -p 8000:8000 --restart=always \
              --env-file /root/web_service_test/.env \
              crpi-kdr9fgca88mf2q5d.cn-hangzhou.personal.cr.aliyuncs.com/kktt_mic/web_service_test:latest
